---
version: '3.2'

networks:
  infra_default:
    external: true
  st_network:
    external: true

services:
  postgresql:
    image: postgres:9.6
    hostname: st-postgresql
    networks:
      st_network:
        aliases:
          - st-postgresql
    command: postgres -c max_connections=300
    environment:
      - POSTGRES_DB=st
      - POSTGRES_USER=st
      - POSTGRES_PASSWORD=st
    restart: unless-stopped
    ports:
      - 5432:5432

  app:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ./media_root:/usr/src/media_root
      - ./static_root:/usr/src/static_root
    environment:
      - DB_NAME=st
      - DB_USER=st
      - DB_HOST=st-postgresql
      - DB_PASSWORD=st
      - DB_PORT=5432
      - DEBUG='true'
    restart: unless-stopped
    hostname: st-app
    networks:
      infra_default:
        aliases:
          - st-app
      st_network:
        aliases:
          - st-app
    ports:
      - 8000:8000
    depends_on:
      - postgresql
